services:
  # Game environment service
  game-env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game-env
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY:-:0}
      
    # Volume mounts
    volumes:
      # Mount source code for development
      - .:/app
      # Mount ROMs directory
      - ./roms:/app/roms:ro
      # For X11 forwarding (GUI support)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
    # Network configuration
    ports:
      - "8080:8080"
      
    # Security options for X11
    security_opt:
      - seccomp:unconfined
      
    # Interactive mode
    stdin_open: true
    tty: true
    
    # Default command - can run server mode or interactive
    command: ["python", "main.py", "--help"] 